config/routes.rb
Rails.application.routes.draw do

  resources :lists
  get 'lists/:list_id/bookmarks/new', to: 'lists#new_bookmark', as: 'new_bookmark'
  post 'lists/:list_id/bookmarks', to: 'lists#create_bookmark', as: 'bookmarks'
  delete 'bookmarks/:id', to: 'lists#destroy_bookmark'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie_id, presence: true
  validates :list_id, presence: true
  belongs_to :movie
  belongs_to :list
  validates :list, uniqueness: { scope: :movie, message: "Unique movie in the list" }
  has_one_attached :photo
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks

  end

  def new_bookmark
    @bookmark = Bookmark.new
  end

  def create_bookmark
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = List.find(params[:list_id])
    @bookmark.save

    redirect_to list_path(params[:list_id])
  end

  def destroy_bookmark
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(params[:id])
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/delete.html.erb
<h1>Lists#delete</h1>
<p>Find me in app/views/lists/delete.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>
<li><%= link_to 'new', new_list_path %></li>

app/views/lists/new.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>
<%= form_with model: @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/lists/new_bookmark.html.erb
<%= simple_form_for @bookmark do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<%= link_to "Delete",
  list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<li><%= link_to 'new bookmark', new_bookmark_path(@list) %></li>

<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.movie.title %></li>
    <%= cl_image_tag(bookmark.photo.key,
      width: 400, height: 300, crop: :fill) %>
    <li><%= bookmark.comment %></li>
    <li><%= link_to "Delete", "/bookmarks/#{bookmark.id}", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
    ..............
  <% end %>
</ul>